jenkins:
  systemMessage: "DevTinder CI/CD Pipeline"
  numExecutors: 2
  mode: NORMAL

plugins:
  required:
    - pipeline
    - git
    - nodejs
    - docker-workflow

nodejs:
  installations:
    - name: "nodejs"
      home: "C:\\Program Files\\nodejs"
      properties:
        - installSource:
            installers:
              - nodeJSInstaller:
                  id: "18.x"

environment:
  variables:
    - key: "NODE_ENV"
      value: "production"
    - key: "DOCKER_HOST"
      value: "npipe:////./pipe/docker_engine" 