version: '3.8'

services:
  # Frontend service
  frontend:
    build:
      context: .  # Root directory (where the Dockerfile is)
      dockerfile: Dockerfile  # The Dockerfile in the frontend folder
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - NEXT_PUBLIC_API_URL=http://localhost:4000  # Backend URL for the frontend
    depends_on:
      - backend  # Ensures backend starts before frontend
    networks:
      - devtinder-network
    restart: unless-stopped

  # Backend service
  backend:
    build:
      context: ./backend  # Context for the backend service
      dockerfile: Dockerfile  # The Dockerfile in the backend folder
    ports:
      - "4000:4000"
      - "4000:4000/udp"  # For WebSocket connections
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/devtinder  # MongoDB URI for backend
      - JWT_SECRET=your_jwt_secret_key_here  # Ensure you set a secure key
      - FRONTEND_URL=http://localhost:3001  # URL of the frontend service
    depends_on:
      - mongodb  # Ensures MongoDB starts before backend
    networks:
      - devtinder-network
    restart: unless-stopped

  # MongoDB service
  mongodb:
    image: mongo:latest
    ports:
      - "27019:27017"  # Changed host port to 27019 to avoid conflict
    volumes:
      - mongodb-data:/data/db  # Persist MongoDB data
    networks:
      - devtinder-network
    restart: unless-stopped

# Network definition
networks:
  devtinder-network:
    driver: bridge

# Volume for MongoDB data
volumes:
  mongodb-data:
